
/*

*/

POST  http://localhost:8080/books
Content-Type: application/json

{"bookid":1,"title": "Spring in Action","author": "Craig Walls"}


HTTP/1.1 200  - OK
content-length: 0
date: Thu, 17 Mar 2022 09:15:33 GMT
connection: close


###
GET  http://localhost:8080/books/


HTTP/1.1 200  - OK
content-type: application/json
transfer-encoding: chunked
date: Thu, 17 Mar 2022 09:15:38 GMT
connection: close


###
PUT  http://localhost:8080/books
Content-Type: application/json
{"bookid": 3,"title": "Spring in Acton 2nd Ed","author": "Craig Walls"}


HTTP/1.1 200  - OK
content-length: 0
date: Thu, 17 Mar 2022 09:14:47 GMT
connection: close


###
DELETE  http://localhost:8080/books/2


HTTP/1.1 200  - OK
content-length: 0
date: Thu, 17 Mar 2022 09:14:16 GMT
connection: close